name: docker2
version: 4.5.0
description: Simple library for viewing and controlling docker images and containers.
repository: https://github.com/noojee/docker2
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  args: ^2.0.0
  dcli: ^4.0.0
  path: ^1.8.0
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.0.0
